import = [
	"~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

live_config_reload = true

[window]
opacity = 0.90

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"
